version: '2'
services:
    mysql:
        image: mysql:5.6.36
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=airflow

    webserver:
        build: .
        restart: always
        depends_on:
            - mysql
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - MYSQL_HOST=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
